### ISSUE TITLE
Create cool welcome page

### ISSUE THREAD

**Issue by maryanchuk04** [maryanchuk04/stud-city#13]
### Create welcome page for user in Client side

**_The idea is that this page should be the first that the user sees and from it he can go to the authorization page or register a new account_**

_Pls @Serhiy-dotcom @Varvara-Maria @Vova-Romaniuk I want to hear your opinion:)_

Something like this:
![image](https://user-images.githubusercontent.com/64914675/217265913-b9b60d12-c8c6-4b3b-9350-cd0538b9809a.png)

or this 
![image](https://user-images.githubusercontent.com/64914675/217266173-9020f7ef-2ca4-45f2-876f-37523619df04.png)

**Comment by Serhiy-dotcom** [comment]
I like the overall concept of "Welcome page", though the first option for me looks like too much stuff going on there, and the second one is probably too simple. So my suggestion is to create something in the middle between those two, and also to add some floating stuff so that the page looks more alive and like there is some stuff going on there.
Let me know your thoughts everyone.

**Comment by maryanchuk04** [comment]
> I like the overall concept of "Welcome page", though the first option for me looks like too much stuff going on there, and the second one is probably too simple. So my suggestion is to create something in the middle between those two, and also to add some floating stuff so that the page looks more alive and like there is some stuff going on there.
> Let me know your thoughts everyone.

LGTM:)

**Comment by maryanchuk04** [comment]
Also we can implement something like this: 
![image](https://user-images.githubusercontent.com/64914675/217269578-8d143f32-3eec-4451-a1dc-601c7cb610b1.png)
or another variant 

![image](https://user-images.githubusercontent.com/64914675/217269656-f35d63ab-bb04-4151-aba8-21441445ec67.png)

**Comment by maria2908** [comment]
can users click on the menu and switch to, for example, Contact?

вт, 7 лют. 2023 р. о 15:17 MaksMaryanchuk ***@***.***> пише:
