### ISSUE TITLE
Question about user roles

### ISSUE THREAD

**Issue by maryanchuk04** [maryanchuk04/stud-city#25]
Guys we must discus some task, in our project we have **Teachers** and **Student** role. We must handler this when we create user profile (Registration new user). If you have some ideas pls attach below this question.

Have a nice day!

@maryanchuk04 @Serhiy-dotcom @Varvara-Maria @Vova-Romaniuk

**Comment by Serhiy-dotcom** [comment]
Hello everybody! Great suggestion Maks, I think we should add additional field probably a Select but fancier, when user try to register on our website, and he will have two options to either be a student or a teacher. I attached small sketch of how I think it should look like.
PS: don't judge too hursh)
![image](https://user-images.githubusercontent.com/65117661/217751588-4f8617f0-bf66-402a-a91c-206da760f2c7.png)

**Comment by Varvara-Maria** [comment]
Hi guys,

**Comment by maryanchuk04** [comment]
> Hello everybody! Great suggestion Maks, I think we should add additional field probably a Select but fancier, when user try to register on our website, and he will have two options to either be a student or a teacher. I attached small sketch of how I think it should look like. PS: don't judge too hursh)
 ![image](https://user-images.githubusercontent.com/65117661/217751588-4f8617f0-bf66-402a-a91c-206da760f2c7.png)



Serhio, I fully support this idea, it's an interesting thing, you just need to implement it in a cool way on the registration page

**Comment by maria2908** [comment]
Hi guys, I think, those two buttons must be in the beginning, when user come at the page, he sees this two buttons, than he clicks and can create or create

**Comment by maryanchuk04** [comment]
> Hi guys, I think, those two buttons must be in the beginning, when user come at the page, he sees this two buttons, than he clicks and can create or create

Are you suggesting to show only 2 buttons at first? To me it will look so-so, only 2 buttons...

**Comment by Serhiy-dotcom** [comment]
> Hi guys, I think, those two buttons must be in the beginning, when user come at the page, he sees this two buttons, than he clicks and can create or create

I like the idea, but only if the registration process going to be different for whether it's a teacher or a student. If the fields and data we get from user are the same, I suggest we just place it lower as this data isn't that important comparing to username, 
email, password and etc. Also we can first take those data(username, email, password) and then forward user to choose his type, that's another way to build it I think.

**Comment by maryanchuk04** [comment]
I also have an idea to make a so-called complete registration, it will be a separate page to which the user will be redirected after filling in the fields (email and password) and after confirming the e-mail. (we can add more information)

**Comment by Vova-Romaniuk** [comment]
Dobruden` everybody, I think these buttons should be on the registration page, but you need to think about whether they will be buttons or maybe a pop-up list. However, you can make a step-by-step registration and choose a role at one of the steps
Good luck! Have a nice day :)

**Comment by Serhiy-dotcom** [comment]
What kind of info do you have in mind of getting? Is it info to fill up his profile and something like that, or you suggesting to get such info as if he is a student or a teacher on a seperate  page and etc?

**Comment by maria2908** [comment]
To be honest, I don't completely understood you. I think we can discuss it
in a meeting

Чт, 9 февр. 2023 г. в 09:11, MaksMaryanchuk ***@***.***>:

**Comment by Serhiy-dotcom** [comment]
> Dobruden` everybody, I think these buttons should be on the registration page, but you need to think about whether they will be buttons or maybe a pop-up list. However, you can make a step-by-step registration and choose a role at one of the steps Good luck! Have a nice day :)

I like the idea of step by step registation, I think LinkedIn has similar way of registrating users, so I'm only up for it!

**Comment by maryanchuk04** [comment]
Yeap, step by step, this is what I meant, but better named! 
@Vova-Romaniuk Thanks

Something like this: 


![Image](https://user-images.githubusercontent.com/64914675/217756774-c408a9c1-fd06-442d-b55b-5a1faeb21002.png)

**Comment by Serhiy-dotcom** [comment]
I like it very much!!! I think @Vova-Romaniuk should work on it as he already working on #12 issue

**Comment by maryanchuk04** [comment]
I think this can be the next task

**Comment by Vova-Romaniuk** [comment]
Yeap, I also think about it)

To work!

**Comment by maryanchuk04** [comment]
### We have registration: 

1. User input email and password  (with again input pass)
2. User get Confirmation code to email
3. User input verify code in confirmation page.
4. If all good, user redirect to (step-by-step page)

**_What about this?_**

**Comment by Serhiy-dotcom** [comment]
Sounds good to me! Although we need to know what to get from user in step-by-step page, but we can discuss it in comment section of that issue later:)
