### ISSUE TITLE
SMS verification frontend

### ISSUE THREAD

**Issue by maryanchuk04** [maryanchuk04/stud-city#44]
In the confirmation page add ability enter phone number. 

As for the design of this, you need to discuss and figure it out...
@maryanchuk04 @Serhiy-dotcom @Varvara-Maria @Vova-Romaniuk

**Comment by maryanchuk04** [comment]
I think we must have ready email verification page, and to think about this option

**Comment by Serhiy-dotcom** [comment]
> I think we must have ready email verification page, and to think about this option

Agree let's do email verification first, and then we will deal with phone no need to rush things out
