### ISSUE TITLE
Edit profile api

### ISSUE THREAD

**Issue by maryanchuk04** [maryanchuk04/stud-city#92]
Implement api for change user information.

**Description**

> Create api for this functional. 
> Add new service for user.

**Comment by mohammed0xff** [comment]
I would love to help.
Can you elaborate more on that ?
is it `UserController` that provide actions for user functionalities like : 
- change UserName 
- change/add PhoneNumber 
?

**Comment by maryanchuk04** [comment]
Yeap, something that, I think this must be UserController with action which provide changing data about user! (PUT or POST method)

**Comment by maryanchuk04** [comment]
@mohammed0xff  if you want implement this you must create new branch with number of issue, and create PR add me to reviewers!
Thanks!!!

**Comment by mohammed0xff** [comment]
Thank you.
On my way ..
